<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxEFBu2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxEFBu2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxEFBu2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxEFBu2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxEFBu2\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxEFBu2',
    'container.build_id' => 'ab2c5d41',
    'container.build_time' => 1590854935,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxEFBu2');
