<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWfcZtNO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWfcZtNO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWfcZtNO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWfcZtNO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWfcZtNO\App_KernelDevDebugContainer([
    'container.build_hash' => 'WfcZtNO',
    'container.build_id' => 'b314c1b2',
    'container.build_time' => 1608478101,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWfcZtNO');
