<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6liVLFq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6liVLFq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6liVLFq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6liVLFq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6liVLFq\App_KernelDevDebugContainer([
    'container.build_hash' => '6liVLFq',
    'container.build_id' => '683a790c',
    'container.build_time' => 1590850447,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6liVLFq');
